
name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t my-image .
        docker tag my-image:latest 025066249719.dkr.ecr.ap-south-1.amazonaws.com/aziz-repo:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 025066249719.dkr.ecr.ap-south-1.amazonaws.com/aziz-repo:latest

    - name: Update ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: taskDef.json
        container-name: azizcontainer
        image: 025066249719.dkr.ecr.ap-south-1.amazonaws.com/aziz-repo:latest

    - name: Deploy to ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: AzizService
        cluster: AzizCluster
        wait-for-service-stability: true
